name: Terraform CI/CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deploy_apps:
        description: 'Deseja realizar o deploy das aplicações?'
        required: true
        type: boolean
        default: false
      confirm_action:
        description: 'Digite "confirmar" para prosseguir com o deploy manual'
        required: true
        type: string
  pull_request:
    branches: [ main ]
  
env:
  SECRET_NAME: "soat/k8s/kubeconfig"

jobs:
  test-and-analyze:
    name: 'Test and Analyze'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Checkov Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          soft_fail: true

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   
        with:
          args: >
            -Dsonar.verbose=true

      - name: SonarCloud Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  terraform:
    name: 'Terraform Plan and Apply EKS'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      TF_VAR_cluster_name: ${{ vars.CLUSTER_NAME }}
      TF_VAR_cluster_version: ${{ vars.CLUSTER_VERSION }}
      TF_VAR_node_count: ${{ vars.NODE_COUNT }}
      TF_VAR_node_flavor: ${{ vars.NODE_FLAVOR }}
      TF_VAR_create_user_function_url: ${{ vars.CREATE_USER_FUNCTION_URL }}
      TF_VAR_identify_client_function_url: ${{ vars.IDENTIFY_CLIENT_FUNCTION_URL }}
      TF_VAR_mercadopago_secret: ${{ secrets.MERCADOPAGO_SECRET }}
      TF_VAR_mercadopago_external_pos_id: ${{ secrets.MERCADOPAGO_EXTERNAL_POS_ID }}
      TF_VAR_mercadopago_user_id: ${{ secrets.MERCADOPAGO_USER_ID }}
      TF_VAR_mercadopago_token: ${{ secrets.MERCADOPAGO_TOKEN }}
      TF_VAR_rabbitmq_user: ${{ secrets.RABBITMQ_USER }}
      TF_VAR_rabbitmq_password: ${{ secrets.RABBITMQ_PASS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Test
        run: terraform test -var="deploy_apps=false"

      - name: Terraform Plan
        run: terraform plan -var="deploy_apps=${{ github.event.inputs.deploy_apps || 'false' }}" -input=false -out=tfplan

      - name: Terraform Apply
        if: |
          github.ref == 'refs/heads/main' && github.event_name == 'push' || 
          (github.event_name == 'workflow_dispatch' && github.event.inputs.confirm_action == 'confirmar')
        run: terraform apply -auto-approve -var="deploy_apps=${{ github.event.inputs.deploy_apps || 'false' }}" -input=false tfplan

      - name: Get Kubeconfig Output and Save to Secrets Manager
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          KUBECONFIG_CONTENT=$(terraform output -raw cluster_kubeconfig_content)
          
          aws secretsmanager put-secret-value --secret-id ${{ env.SECRET_NAME }} --secret-string "$KUBECONFIG_CONTENT"
