name: Terraform CI/CD for Magalu Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest
    env:
      MGC_ACCESS_KEY: ${{ secrets.MGC_ACCESS_KEY }}
      MGC_SECRET_KEY: ${{ secrets.MGC_SECRET_KEY }}
      TF_VAR_rails_app_image_tag: "1.2.0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false tfplan