name: Terraform CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SECRET_NAME: "soat/k8s/kubeconfig"

jobs:
  terraform:
    name: 'Terraform Plan and Apply EKS'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      TF_VAR_rails_app_image_tag: ${{ vars.RAILS_APP_IMAGE_TAG }}
      TF_VAR_cluster_name: ${{ vars.CLUSTER_NAME }}
      TF_VAR_cluster_version: ${{ vars.CLUSTER_VERSION }}
      TF_VAR_node_count: ${{ vars.NODE_COUNT }}
      TF_VAR_node_flavor: ${{ vars.NODE_FLAVOR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
      
      - name: Get Database Secret from AWS Secrets Manager
        id: get-db-secret
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            RAILS_DATABASE_URL, soat/db/database_url

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan
        env:
          TF_VAR_database_url: ${{ steps.get-db-secret.outputs.RAILS_DATABASE_URL }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false tfplan
        env:
          TF_VAR_database_url: ${{ steps.get-db-secret.outputs.RAILS_DATABASE_URL }}

      - name: Get Kubeconfig Output and Save to Secrets Manager
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          KUBECONFIG_CONTENT=$(terraform output -raw cluster_kubeconfig_content)
          
          aws secretsmanager put-secret-value --secret-id ${{ env.SECRET_NAME }} --secret-string "$KUBECONFIG_CONTENT"
